server:
  port: 8080

spring:
  application:
    name: concert-wishlist
  
  # Azure SQL Database Configuration
  datasource:
    url: jdbc:mysql://concert-wishlist.mysql.database.azure.com:3306/concert_wishlist?useSSL=true&requireSSL=true
    username: danny
    password: Saku1892
    driver-class-name: com.mysql.cj.jdbc.Driver  # Changed from SQL Server
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # Changed from SQLServerDialect
        format_sql: true
        
  # Security & OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: 04ce6df4b47645e9be5cf4824d8ca1f1
            client-secret: 2306912a76c446389845d3029d88bee8
            authorization-grant-type: authorization_code
            redirect-uri: "https://concert-wishlist-app-e5dwa5dka0c6b3ev.polandcentral-01.azurewebsites.net/login/oauth2/code/spotify"
            scope: user-read-private,user-read-email
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id

# Spotify API Configuration
spotify:
  api:
    base-url: https://api.spotify.com/v1
  client-id: 04ce6df4b47645e9be5cf4824d8ca1f1
  client-secret: 2306912a76c446389845d3029d88bee8

# Logging Configuration
logging:
  level:
    com.teamrhythm: INFO
    org.springframework.security: WARN